from sqlalchemy import Column, Integer, String
from sqlalchemy.orm import declarative_base
import sqlalchemy as db

Base = declarative_base()

class BronzeRow(Base):
    __tablename__ = "bronze_layer"
    __table_args__={"schema": "bronze"}

    id=db.Column(db.String(200), primary_key=True)
    resultId = Column(String)
    raceId = Column(String)
    driverId = Column(String)
    constructorId = Column(String)
    number = Column(String)
    grid = Column(String)
    position = Column(String)
    positionOrder = Column(String)
    points = Column(String)
    laps = Column(String)
    milliseconds = Column(String)
    fastestLap = Column(String)
    rank = Column(String)
    fastestLapSpeed = Column(String)
    statusId = Column(String)
    year = Column(String)
    round = Column(String)
    lat = Column(String)
    lng = Column(String)
    alt = Column(String)
    number_drivers = Column(String)
    lap = Column(String)
    position_laptimes = Column(String)
    milliseconds_laptimes = Column(String)
    lap_pitstops = Column(String)
    milliseconds_pitstops = Column(String)
    stop = Column(String)
    driverStandingsId = Column(String)
    points_driverstandings = Column(String)
    position_driverstandings = Column(String)
    wins = Column(String)
    constructorStandingsId = Column(String)
    points_constructorstandings = Column(String)
    position_constructorstandings = Column(String)
    wins_constructorstandings = Column(String)
    positionText = Column(String)
    name_x = Column(String)
    name_y = Column(String)
    location = Column(String)
    country = Column(String)
    forename = Column(String)
    surname = Column(String)
    nationality = Column(String)
    nationality_constructors = Column(String)
    positionText_constructorstandings = Column(String)
    positionText_driverstandings = Column(String)
    status = Column(String)
    duration = Column(String)
    date = Column(String)
    quali_date = Column(String)
    dob = Column(String)
    sprint_date = Column(String)
    time = Column(String)
    fastestLapTime = Column(String)
    time_races = Column(String)
    quali_time = Column(String)
    sprint_time = Column(String)
    time_laptimes = Column(String)
    time_pitstops = Column(String)
    url_x = Column(String)
    url_y = Column(String)
    url = Column(String)
    url_constructors = Column(String)
    circuitRef = Column(String)
    driverRef = Column(String)
    constructorRef = Column(String)
    code = Column(String)
    circuitId = Column(String)
    fp1_date = Column(String)
    fp1_time = Column(String)
    fp2_date = Column(String)
    fp2_time = Column(String)
    fp3_date = Column(String)
    fp3_time = Column(String)
    name=Column(String)
    dateId=Column(String)